### PR TITLE
Update recastai SDK to v3

### PR DESCRIPTION
**Pull request by loulafripouille**
related to #3

### CODE REVIEW

**Review by ouadie-lahdioui — APPROVED** [review]
LGTM 👍 thank you @laudeon

**Comment by loulafripouille** [comment]
Hello ! 
I installed again your package today, but it does not include the latest changes. Is it ok for you to push the latest changes of this merge as a new version?
Thanks in advance!

**Comment by ouadie-lahdioui** [comment]
Hi @laudeon,

The latest version 1.0.6 published on npm content all the modifications (recast dependency v^3.7.0, a json object on readme file, ...)

let me know if you still have issue or if you want me publish a new version 1.0.7 !

**Comment by loulafripouille** [comment]
Oh ok, I did not noticed it as there is no 1.0.6 tag in the repo thus it is my bad, I did not update my dependency version ;).
Thanks a lot!

**Pull request merged**
